default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: adela_production
  username: postgres
  password: secretpassword
  host: 0.0.0.0
  port: 5433

test:
  <<: *default
  database: adela_test
  username: postgres
  password: secretpassword
  host: 0.0.0.0
  port: 5433

production:
  <<: *default
  database: adela_production
  username: postgres
  host: postgres
  password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
